# Generated by Django 2.2.12 on 2020-06-02 10:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0004_testtt_jhjh'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='customtext',
            name='title',
        ),
        migrations.RemoveField(
            model_name='testtt',
            name='jhjh',
        ),
    ]
